### ISSUE TITLE
Using Sasi for full text search

### ISSUE THREAD

**Issue by measwel** [xedin/sasi#10]
Good day,

I am planning to use sasi for full text searching a varchar cassandra field called description. In relation I have a few questions:

1. Can I have both Sasi and a 'normal' secondary index on the cassandra table? I need to index an email field next to the description field that I want to index with sasi. Should I also use a sasi index on the email field?

2. The user can input a search query containing multiple terms, such as: 'cats and dogs'. How would I search in sasi based on this search query? Should I tokenize the search query myself? 

3. How would I implement an OR serach ( 'cats' OR 'dogs' in description text ) ?

4.  How would I implement an AND serach ( 'cats' AND 'dogs' in description text ) ?

5. Which locales does the sasi tokenizer support? How should I choose the tokenization locale when creating the index, not knowing the eventual user locale that will be used?

Thank you.

**Comment by xedin** [comment]
Hi, @measwel ! Thanks for your interest in the project! SASI has been completely merged and is considered a part of Apache Cassandra, so I'd suggest you to open an issue at https://issues.apache.org/jira and discuss your questions there to have a broader audience covered.

Here is couple of answers for me:

1. Yes, you can use different indexes on different fields but unfortunately you can't use them in the same query, this is currently a limitation of C* secondary index API.

2. Yes, search query would be tokenized based on the settings specified in the index field itself.

3. There is CQL syntax for that  you can do foo = 'x' OR foo = 'y'.
4. Ditto.

5. As many as underlying implementation supports (jflex), I suggest you to take a look at https://github.com/apache/cassandra/blob/trunk/doc/SASI.md (Text Analysis section). I think it supports European languages, Chinese, Japanese and more!

**Comment by measwel** [comment]
Thank you Pavel! For my understanding:

1. I split the data, so my sasi index is in a separate table now. 

2. This means cassandra will take care of the tokenization of the search query and I do not have to worry about it? 

3. Suppose the user enters as query: 'a white shepherd dog'. How would I search for that? 
foo= '%white%' OR foo='%shepherd%' OR foo='%dog%'
Or should I supply the entire query : foo='%a white shepherd dog%'

If I must supply the separate terms to the search query, wouldn't I have to do the tokenization manually then?

4. Same as 3.

5. OK. Can I set multiple locales when I create the index? At creation time I do not know the locale that will be used for the description. How would I make sure 2 locales are supported on the description field?

**Comment by xedin** [comment]
1. You could, it's up to you, it's just C* in general doesn't support mixing indexes in the query.
2. Yes.
3/4. It's going to be tokenized and based on the type of the index, so it could be either depending on what you want to archive, I suggest you take a look at https://github.com/apache/cassandra/blob/trunk/doc/SASI.md
5. Usually you'd create different fields/indexes for different locales because it's not a good idea to mix the data that way.

**Comment by measwel** [comment]
Thank you again!

3/4. If I understand it well, the best for me is simply to provide the whole user query as the LIKE term and let cassandra do the tokenizing and searching for all the terms in the query?

5. Understood.

**Comment by xedin** [comment]
3/4. Most likely that would be the best option, yes. Since you can configure tokenization etc. in the index itself.

**Comment by measwel** [comment]
Full text search works wonderfully! Thank you Pavel.
Now I must implement geospatial search based on geohashing. 
Then I will be a happy camper.

This will allow me to use only cassandra without elastic search or solr to do full text search and geospatial search.

**Comment by measwel** [comment]
Pavel, another question: I need to filter data based on a category. Trying with:
SELECT  * FROM "post" WHERE "category" IN ?    ; with params: [["category"]] leads to:
`"IN predicates on non-primary-key columns (category) is not yet supported"`

You said, that one cannot combine a sasi index and a non-sasi filter in one query. I suppose I will need to use a sasi index to do the filtering on category. My need is to be able to filter on an array of category values such as: ['cat1', 'cat2']. The results need to be in one of the given categories. How would I do that with a Sasi index?

I am trying with the following table:
```
CREATE TABLE arbotti.post (
    uuid uuid,
    created timestamp,
    category text,
    description_en text,
    description_pl text
    PRIMARY KEY (uuid, created)
) WITH CLUSTERING ORDER BY (created DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX post_category_idx ON arbotti.post (category) USING 'org.apache.cassandra.index.sasi.SASIIndex' WITH OPTIONS = {'mode': 'PREFIX'};
CREATE CUSTOM INDEX post_description_en_idx ON arbotti.post (description_en) USING 'org.apache.cassandra.index.sasi.SASIIndex' WITH OPTIONS = {'tokenization_locale': 'en', 'tokenization_skip_stop_words': 'true', 'analyzer_class': 'org.apache.cassandra.index.sasi.analyzer.StandardAnalyzer', 'tokenization_normalize_lowercase': 'true', 'mode': 'CONTAINS', 'analyzed': 'true', 'tokenization_enable_stemming': 'true'};
CREATE CUSTOM INDEX post_description_pl_idx ON arbotti.post (description_pl) USING 'org.apache.cassandra.index.sasi.SASIIndex' WITH OPTIONS = {'tokenization_locale': 'pl', 'tokenization_skip_stop_words': 'true', 'analyzer_class': 'org.apache.cassandra.index.sasi.analyzer.StandardAnalyzer', 'tokenization_normalize_lowercase': 'true', 'mode': 'CONTAINS', 'analyzed': 'true', 'tokenization_enable_stemming': 'true'};
```

But executing the following query:
select * from post where description_en like 'aa' and category ='cat1';
Leads to:
`InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"`

UPDATE: I have implemented my usecase by:

1. Setting category as the partition key.
2. Setting a sasi contains index on description.

Now I run seperate queries for each category like this:
`SELECT  * FROM "post" WHERE category = 'cat1' and description like 'some query' ;`
Then I merge the results.  

I realise that this is a suboptimal solution, but I have not found a way to query for all needed categories in one query. If there is a way to do this, I would like to find it out.

**Comment by measwel** [comment]
Can somebody please enlighten me regarding cassandra partitioning? I do not understand the following:

- On one hand it is advisable to choose a partition key with high cardinality so that the data is well distributed over the partitions and nodes. I have seen examples advising to use a uuid as the partition key for this reason. I understand that this approach works fine when fetching one record.

- On the other hand however, it is also said, that one should try to minimise the number of read partitions when fetching data. If I am to fetch posts within some category, then ideally I want all those posts to be present on the same node. But this will never be the case if an uuid is the partition key. So in this case it seems much better to group records by choosing the category ID as the partition key. 

Can somebody please explain to me how a partition key should be chosen in order to optimise data retrieval from cassandra?

**Comment by xedin** [comment]
@measwel I suggest you e-mail user@cassandra.apache.org and ask these and any other questions you have about Apache Cassandra there, that would be a right forum to ask your questions.

**Comment by measwel** [comment]
Thank you Pavel. I have done as you suggested.
