### ISSUE TITLE
add full CQL3 (clustering, statics) indexing support

### ISSUE THREAD

**Issue by xedin** [xedin/sasi#3]
Requires extending TokenTree to be a tree of multiple token layers.

**Comment by doanduyhai** [comment]
Is support for collection and map key index scheduled or is it completely out of scope ?

**Comment by xedin** [comment]
@doanduyhai it definitely is in scope, but we want to improve clustering columns support first.

**Comment by doanduyhai** [comment]
Great to hear. So excited, can't wait to play with!

**Comment by xedin** [comment]
clustering support has been added as part of CASSANDRA-10661, statics are not on the roadmap.
