### ISSUE TITLE
Availability on 2.x release

### ISSUE THREAD

**Issue by thanigaiv** [xedin/sasi#6]
I would like to know if Sasi indexes are planned to be supported in a future 2.x release? or would it work only on 3.4 and above?

**Comment by xedin** [comment]
@thanigaiv going forward only 3.4 and 2.0.17 are going to be supported, since porting it to all of the 2.x series is not a trivial matter and would require changes to Cassandra 2.x which currently in maintenance only mode.

**Comment by thanigaiv** [comment]
Thanks @xedin!
